const app=document.querySelector("#app"), account=document.querySelector("#account");
const state={token:localStorage.token||"",user:JSON.parse(localStorage.user||"null")};

function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function api(url,opts={}){opts.headers={"Content-Type":"application/json",...(opts.headers||{})};if(state.token)opts.headers.Authorization="Bearer "+state.token;const r=await fetch(url,opts);const d=await r.json();if(!r.ok)throw Error(d.error||"Something went wrong");return d}
function renderAccount(){account.innerHTML=state.user?`<span>${esc(state.user.name)}</span><button class="ghost" onclick="logout()">Log out</button>`:`<button onclick="authModal('login')">Sign in</button>`}
function logout(){localStorage.clear();state.token="";state.user=null;renderAccount();location.hash="#/"}
function authModal(mode="login"){app.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div><div class="sectionhead"><h2>${mode==="login"?"Welcome back":"Create your account"}</h2><button class="ghost" onclick="document.querySelector('#modal').remove()">×</button></div><form class="form" onsubmit="submitAuth(event,'${mode}')">${mode==="register"?'<input name="name" placeholder="Full name" required>':''}<input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Password" required>${mode==="register"?'<select name="role"><option value="renter">I am looking for a home</option><option value="landlord">I am a landlord</option></select>':''}<button>${mode==="login"?"Sign in":"Create account"}</button></form><p class="muted">${mode==="login"?'New here?':'Already have an account?'} <a href="#" onclick="event.preventDefault();authModal('${mode==="login"?"register":"login"}')">${mode==="login"?"Create account":"Sign in"}</a></p></div></div>`)}
async function submitAuth(e,mode){e.preventDefault();const f=new FormData(e.target),body=Object.fromEntries(f);try{const d=await api("/api/"+(mode==="login"?"login":"register"),{method:"POST",body:JSON.stringify(body)});state.token=d.token;state.user=d.user;localStorage.token=d.token;localStorage.user=JSON.stringify(d.user);document.querySelector("#modal").remove();renderAccount();route()}catch(err){alert(err.message)}}
function listingCard(p){return `<article class="card"><div class="photo" style="background-image:url('${esc(p.image)}')">${p.verified?'<span class="badge">✓ Verified</span>':''}<button class="heart" onclick="toggleFav(event,${p.id})">♡</button></div><div class="body"><div class="price">$${Number(p.rent).toLocaleString()} <span class="muted">/ month</span></div><h3>${esc(p.title)}</h3><div class="muted">${p.bedrooms} bd · ${p.bathrooms} ba · ${Number(p.sqft).toLocaleString()} sq ft</div><p class="muted">📍 ${esc(p.city)}, ${esc(p.state)}</p><div class="tags">${(Array.isArray(p.amenities)?p.amenities:p.amenities.split(",")).slice(0,3).map(x=>`<span class="tag">${esc(x)}</span>`).join("")}</div><a class="btn" href="#/listing/${p.id}">View listing</a></div></article>`}
async function home(){const listings=await api("/api/listings");app.innerHTML=`<section class="hero"><div><h1>Find a place you'll love to call home.</h1><p>A simpler way to discover apartments, connect with landlords and schedule your next tour.</p><form class="searchbox" onsubmit="search(event)"><input name="city" placeholder="City, neighborhood or ZIP"><select name="maxRent"><option value="">Any rent</option><option value="1500">$1,500 max</option><option value="2000">$2,000 max</option><option value="2500">$2,500 max</option><option value="3000">$3,000 max</option></select><select name="bedrooms"><option>Any</option><option>1</option><option>2</option><option>3</option></select><button>Search apartments</button></form></div></section><section class="wrap"><div class="sectionhead"><h2>Featured apartments</h2><a href="#/search">View all →</a></div><div class="grid">${listings.map(listingCard).join("")}</div></section>`}
async function search(e){e.preventDefault();const f=new FormData(e.target),q=new URLSearchParams();for(const [k,v] of f)if(v&&v!=="Any")q.set(k,v);location.hash="#/search?"+q}
async function searchPage(){const q=new URLSearchParams(location.hash.split("?")[1]||"");const listings=await api("/api/listings?"+q);app.innerHTML=`<section class="wrap"><div class="sectionhead"><div><h1>Apartments for Rent</h1><p class="muted">${listings.length} homes available</p></div><button class="secondary" onclick="location.hash='#/'">New search</button></div><div class="results"><div class="list">${listings.length?listings.map(listingCard).join(""):"<div class='panel'><h2>No matches yet</h2><p>Try a broader city, rent range or bedroom count.</p></div>"}</div><div class="map"></div></div></section>`}
async function listingPage(id){const p=await api("/api/listings/"+id);app.innerHTML=`<section class="wrap"><a href="#/search">← Back to results</a><div class="detail" style="margin-top:18px"><div><div class="gallery" style="background-image:url('${esc(p.image)}')"></div><div class="panel" style="margin-top:18px"><h1>${esc(p.title)}</h1><p class="muted">📍 ${esc(p.address)}, ${esc(p.city)}, ${esc(p.state)} ${esc(p.zip)}</p><div class="price">$${Number(p.rent).toLocaleString()} / month</div><p>${p.bedrooms} bedrooms · ${p.bathrooms} bathrooms · ${Number(p.sqft).toLocaleString()} sq ft</p><p class="muted">Available ${esc(p.available_date)}</p><h3>Description</h3><p>${esc(p.description)}</p><h3>Amenities</h3><div class="tags">${p.amenities.map(x=>`<span class="tag">${esc(x)}</span>`).join("")}</div></div></div><aside class="panel sticky"><h2>$${Number(p.rent).toLocaleString()} <span class="muted">/mo</span></h2><p><strong>${esc(p.landlord_name)}</strong><br><span class="muted">${p.verified?"✓ Verified property":"Property listing"}</span></p><button style="width:100%" onclick="inquiry(${p.id})">Contact landlord</button><button class="secondary" style="width:100%;margin-top:9px" onclick="tour(${p.id})">Schedule a tour</button><button class="ghost" style="width:100%;margin-top:9px" onclick="toggleFav(event,${p.id})">♡ Save apartment</button></aside></div></section>`}
async function toggleFav(e,id){e.stopPropagation();if(!state.user)return authModal("login");try{await api("/api/favorites/"+id,{method:"POST"});alert("Saved status updated");}catch(err){alert(err.message)}}
function inquiry(id){if(!state.user)return authModal("login");app.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div><h2>Contact landlord</h2><form class="form" onsubmit="sendInquiry(event,${id})"><textarea name="message" required>Hello, I'm interested in this apartment. Is it still available?</textarea><button>Send message</button><button type="button" class="secondary" onclick="document.querySelector('#modal').remove()">Cancel</button></form></div></div>`)}
async function sendInquiry(e,id){e.preventDefault();const message=e.target.message.value;try{await api("/api/inquiries",{method:"POST",body:JSON.stringify({propertyId:id,message})});document.querySelector("#modal").remove();alert("Message sent.");}catch(err){alert(err.message)}}
function tour(id){if(!state.user)return authModal("login");app.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div><h2>Request a tour</h2><form class="form" onsubmit="sendTour(event,${id})"><input type="datetime-local" name="tourDate" required><button>Request tour</button><button type="button" class="secondary" onclick="document.querySelector('#modal').remove()">Cancel</button></form></div></div>`)}
async function sendTour(e,id){e.preventDefault();try{await api("/api/tours",{method:"POST",body:JSON.stringify({propertyId:id,tourDate:e.target.tourDate.value})});document.querySelector("#modal").remove();alert("Tour request sent.");}catch(err){alert(err.message)}}
async function dashboard(){if(!state.user){app.innerHTML=`<section class="wrap"><div class="panel"><h2>Sign in to view your dashboard</h2><button onclick="authModal('login')">Sign in</button></div></section>`;return}const d=await api("/api/dashboard");const isL=d.role==="landlord";app.innerHTML=`<section class="wrap"><div class="dash"><aside class="side"><h2>HomeNest</h2><p>${esc(state.user.name)}</p><a href="#/dashboard">Dashboard</a><a href="#/search">Search apartments</a>${isL?'<a href="#/landlord">+ Add property</a>':''}</aside><div><div class="stats"><div class="stat">Saved / Properties<strong>${isL?d.properties.length:d.favorites.length}</strong></div><div class="stat">Messages<strong>${d.inquiries.length}</strong></div><div class="stat">Tours<strong>${d.tours.length}</strong></div><div class="stat">Account<strong>${isL?"Landlord":"Renter"}</strong></div></div><div class="panel" style="margin-top:18px"><h2>${isL?"Your properties":"Saved apartments"}</h2>${isL?d.properties.map(p=>`<p><strong>${esc(p.title)}</strong> · $${Number(p.rent).toLocaleString()}/mo · ${esc(p.city)}</p>`).join("")||"<p class='muted'>No properties yet.</p>":d.favorites.map(listingCard).join("")||"<p class='muted'>No saved apartments yet.</p>"}</div><div class="panel" style="margin-top:18px"><h2>Upcoming / recent tours</h2>${d.tours.map(t=>`<p><strong>${esc(t.title)}</strong> · ${esc(t.tour_date)} · ${esc(t.status)}</p>`).join("")||"<p class='muted'>No tours yet.</p>"}</div></div></div></section>`}
function landlord(){if(!state.user||state.user.role!=="landlord")return authModal("register");app.innerHTML=`<section class="wrap"><div class="panel"><h1>List your property</h1><p class="muted">Publish an apartment so renters can discover it.</p><form class="form" onsubmit="createListing(event)"><input name="title" placeholder="Listing title" required><div class="two"><input name="address" placeholder="Street address" required><input name="city" placeholder="City" required></div><div class="two"><input name="state" placeholder="State" required><input name="zip" placeholder="ZIP code" required></div><div class="two"><input name="rent" type="number" placeholder="Monthly rent" required><input name="sqft" type="number" placeholder="Square feet" required></div><div class="two"><input name="bedrooms" type="number" min="0" placeholder="Bedrooms" required><input name="bathrooms" type="number" step=".5" min=".5" placeholder="Bathrooms" required></div><input name="availableDate" type="date" required><input name="image" placeholder="Image URL (optional)"><textarea name="description" placeholder="Describe the apartment" required></textarea><input name="amenities" placeholder="Amenities, separated by commas"><button>Publish listing</button></form></div></section>`}
async function createListing(e){e.preventDefault();const f=new FormData(e.target),o=Object.fromEntries(f);o.amenities=(o.amenities||"").split(",").map(x=>x.trim()).filter(Boolean);try{await api("/api/listings",{method:"POST",body:JSON.stringify(o)});alert("Listing published.");location.hash="#/dashboard"}catch(err){alert(err.message)}}
function route(){renderAccount();const h=location.hash||"#/";if(h.startsWith("#/listing/"))listingPage(h.split("/")[2]);else if(h.startsWith("#/search"))searchPage();else if(h==="#/dashboard")dashboard();else if(h==="#/landlord")landlord();else home()}
window.addEventListener("hashchange",route);route();
